name: Olympiade
version: '${version}'
main: fr.zadiho.hepickstudio.olympiade.Olympiade
api-version: 1.19
authors: [ ZaDiHo ]
load: POSTWORLD
description: Plugins événementiel Olympiade Saison III regroupant différentes épreuves.
depend:
  - LuckPerms

commands:
  game:
    description: Commande principale du plugin.
    usage: /game <jump|race|pvp>
    aliases: [épreuve]
  host:
    description: Commande des organisateurs.
    usage: /host pseudo
    aliases:
      - h
  spawn:
    description: Commande de téléportation au spawn.
    usage: /spawn
    aliases:
      - lobby
      - hub
  points:
    description: Commande des points
